dist: trusty
sudo: required

language: go
go:
  - 1.8.3
    
go_import_path: github.com/allencloud/pouch

notifications:
  email:
    - shlazww@163.com

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq autoconf automake

script:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo hack/make.sh 